# Generated by Django 6.0.1 on 2026-01-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="currency",
        ),
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.CharField(default="KZT", max_length=3),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_transactions",
                to="wallet.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_transactions",
                to="wallet.wallet",
            ),
        ),
    ]
